package com.utilities.epds;

public class FalloutReportQueries {

	public static final String STATISTICAL_REPORT_MDX_TOTAL_TXNS = "WITH JSON_TRNSCTN AS\r\n" + 
			"(SELECT EQR.REQUEST\r\n" + 
			"FROM SPSMDX_ODS.OPS.ENGINEQUEUERESULTDETAIL EQR\r\n" + 
			"INNER JOIN SPSMDX_ODS.OPS.ENGINEQUEUE EQ\r\n" + 
			"ON EQR.ENGINEQUEUEID=EQ.ENGINEQUEUEID\r\n" + 
			"AND EQ.OPERATION='DELTAEXTRACT' \r\n" + 
			"WHERE EQ.ENGINEBATCHID IN (SELECT MAX(ENGINEBATCHID) FROM SPSMDX_ODS.OPS.ENGINEBATCH)\r\n" + 
			")\r\n" + 
			"SELECT COUNT(*) as Total_number_input_into_EPDSv2 FROM\r\n" + 
			"(SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]ADD[_]EBP[_]PROCESSING%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]ADD[_]ENTIRE[_]FLOW%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]ADD[_]GRP[_]LINKAGE[_]FOR[_]PHO[_]ASSGNMT%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]ADDR%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]AFFL[_]RELATIONSHIP%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]ALT[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]EBP[_]GROUPING[_]ALL[_]BUT[_]SUPPORTING[_]PROV%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]EBP[_]PROCESSING[_]SUPPORTING[_]PROV%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]NTWK%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%GRP[_]EDIT[_]PROFILE%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]ADDR[_]AFF[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]CLAIM[_]ACTION[_]SANCTION%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]EDIT[_]EDUCATION[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]EDIT[_]PROFILE[_]AREA[_]OF[_]FOCUS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]EDIT[_]TERM[_]PDM[_]IND%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]EDIT[_]TITLE%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]GRP[_]LINKAGE[_]FOR[_]POD[_]ASSGNMT%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]GRP[_]RELATNSHIP[_]TO[_]IND[_]CREATE[_]PCP[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]REMOVE[_]PROV[_]ETHNICITY%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]REMOVE[_]PROV[_]LANGUAGE%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]ADD[_]TERM[_]NPI%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EDIT[_]EXIST[_]ADDR%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EDIT[_]EXIST[_]ADDR[_]TERM[_]ORG[_]AFF%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EDIT[_]TERM[_]CLAIM[_]ACTION[_]SANCTION%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]ADD[_]AFF[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]ADD[_]AFF[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]AFF[_]ADD[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]AFF[_]NTWK[_]ADD[_]TERM[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]AREA[_]OF[_]FOCUS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]CONTACT[_]INFO%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]EDIT[_]SCHEDULE[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]EDIT[_]SPECIAL[_]PROGRAMS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]EDIT[_]SPECIALTY%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]EXIST[_]ADDR[_]OFFICE[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]FALLOUT[_]REPORT%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]NEW[_]PROV[_]ENTIRE[_]FLOW%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]NTWK[_]ADD[_]EDIT[_]PATIENT[_]PREFS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]NTWK[_]ADD[_]TERM[_]ACCPT[_]PATNTS[_]IND%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]NTWK[_]ADD[_]TERM[_]DIRECTORY[_]IND%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]NTWK[_]ADD[_]TERM[_]TIMELY[_]FILING%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]ADD[_]ALT[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]ADD[_]EDIT[_]CREDENTIALING[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]ADD[_]EDIT[_]SPECIALTY[_]BOARD[_]CERT%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]ALIAS[_]NAME%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]EDIT[_]DOB[_]GENDER%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]EDIT[_]NAME%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]EDIT[_]TERM[_]ALT[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]PROFILE[_]TERM[_]DATE%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]TERM[_]CASCADE[_]PRACTICE[_]ADDR%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%IND[_]TERM[_]NTWK[_]REIMB[_]NO[_]REPLACEMENTS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]ALT[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]CLAIM[_]ACTION[_]SANCTION%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]EDIT[_]TERM[_]PDM[_]INDS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]FULL[_]FLOW[_]IN[_]EPDSV2%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]PRACTICE[_]ADDR[_]NTWK[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]ADD[_]REMOVE[_]PROV[_]DISTINCTION[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]ADD[_]TERM[_]NPI[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]LEGACY[_]FIELDS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]NAME%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]PRACTICE[_]ADDR[_]ADD[_]EDIT[_]CONTACT[_]INFO%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]REMIT[_]ADDR[_]ADD[_]EDIT[_]CONTACT[_]INFO%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]REMIT[_]ADDR[_]CHANGE[_]REMITTANCE[_]CHECK%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]TERM[_]ALTERNATE[_]ID%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EDIT[_]TERM[_]CLAIM[_]ACTION[_]SANCTION%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EXIST[_]ADDR[_]EDIT[_]OFFICE[_]SERVICES%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EXIST[_]ADDR[_]EDIT[_]SCHEDULE[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EXIST[_]ADDR[_]OFFICE[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]EXIST[_]PRACTICE[_]ADDR[_]EDIT[_]SPECIAL[_]PROGRAMS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]PROFILE[_]ADD[_]EDIT[_]TERM[_]CREDENTIALING[_]DETAILS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]ADD[_]NTWK[_]ALL[_]DATA%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]ADD[_]REIMB%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]ADD[_]REMIT[_]ADDR%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]ADDR[_]PROF[_]ORGS[_]ONLY%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]ADDR[_]PROF[_]ORGS[_]ONLY%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]NTWK[_]REIMB[_]NO[_]REPLACEMENTS%' UNION ALL\r\n" + 
			"SELECT * FROM JSON_TRNSCTN WHERE REQUEST LIKE '%ORG[_]TERM[_]PROFILE%' \r\n" + 
			")CNT";
	
	public static final String STATISTICAL_REPORT_PEGA_SUCCESS_TXNS = "SELECT COUNT(*) as Transaction_successful FROM\r\n" + 
			"(\r\n" + 
			"select * from rpapega_data.pc_auto_robot_work where messagedetails='Transaction Successfully Completed'\r\n" + 
			")";
}
