package com.utilities.epds;

public class SPSAltIdQueries {

	public static final String SPS_IND_ALT_ID_QUERY = "SELECT ALTID_SOR_CD\r\n" + 
			",ALTID_TYPE_CD\r\n" + 
			",ALTID_TXT\r\n" + 
			",PROV_ALTID_EFCTV_DT\r\n" + 
			",PROV_ALTID_TRMNTN_DT\r\n" + 
			",PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			"FROM\r\n" + 
			"(\r\n" + 
			"SELECT COALESCE(XWALK1.CD_VAL_NM,' ') AS ALTID_SOR_CD\r\n" + 
			",COALESCE(XWALK2.CD_VAL_NM,' ') AS ALTID_TYPE_CD\r\n" + 
			",PALT.ALTID_TXT\r\n" + 
			",PALT.PROV_ALTID_EFCTV_DT\r\n" + 
			",PALT.PROV_ALTID_TRMNTN_DT\r\n" + 
			",COALESCE(XWALK3.CD_VAL_NM,'') AS PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			",P.MSTR_PROV_ID\r\n" + 
			"FROM <SPS_DBNAME>.PROV_ALT_IDFCTN PALT\r\n" + 
			"INNER JOIN <SPS_DBNAME>.PROV P\r\n" + 
			"ON P.MSTR_PROV_ID=PALT.MSTR_PROV_ID\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_SOR_CD'\r\n" + 
			")XWALK1\r\n" + 
			"ON XWALK1.CD_VAL_CD=PALT.ALTID_SOR_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_TYPE_CD'\r\n" + 
			")XWALK2\r\n" + 
			"ON XWALK2.CD_VAL_CD=PALT.ALTID_TYPE_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'PROV_ALTID_TRMNTN_RSN_CD'\r\n" + 
			")XWALK3\r\n" + 
			"ON XWALK3.CD_VAL_CD=PALT.PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			"WHERE P.PROV_CTGRY_CD='181'\r\n" + 
			")ALTID\r\n" + 
			"WHERE UPPER(ALTID_SOR_CD)='EPDSV2.0'\r\n" + 
			"AND UPPER(ALTID_TYPE_CD)='LEGACY PROVIDER ID'\r\n" + 
			"AND MSTR_PROV_ID IN(<SPS_ID_LIST>)";

	public static final String SPS_ORG_ALT_ID_QUERY = "SELECT ALTID_SOR_CD\r\n" + 
			",ALTID_TYPE_CD\r\n" + 
			",ALTID_TXT\r\n" + 
			",PROV_ALTID_EFCTV_DT\r\n" + 
			",PROV_ALTID_TRMNTN_DT\r\n" + 
			",PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			"FROM\r\n" + 
			"(\r\n" + 
			"SELECT COALESCE(XWALK1.CD_VAL_NM,' ') AS ALTID_SOR_CD\r\n" + 
			",COALESCE(XWALK2.CD_VAL_NM,' ') AS ALTID_TYPE_CD\r\n" + 
			",PALT.ALTID_TXT\r\n" + 
			",PALT.PROV_ALTID_EFCTV_DT\r\n" + 
			",PALT.PROV_ALTID_TRMNTN_DT\r\n" + 
			",COALESCE(XWALK3.CD_VAL_NM,'') AS PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			",P.MSTR_PROV_ID\r\n" + 
			"FROM <SPS_DBNAME>.PROV_ALT_IDFCTN PALT\r\n" + 
			"INNER JOIN <SPS_DBNAME>.PROV P\r\n" + 
			"ON P.MSTR_PROV_ID=PALT.MSTR_PROV_ID\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_SOR_CD'\r\n" + 
			")XWALK1\r\n" + 
			"ON XWALK1.CD_VAL_CD=PALT.ALTID_SOR_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_TYPE_CD'\r\n" + 
			")XWALK2\r\n" + 
			"ON XWALK2.CD_VAL_CD=PALT.ALTID_TYPE_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'PROV_ALTID_TRMNTN_RSN_CD'\r\n" + 
			")XWALK3\r\n" + 
			"ON XWALK3.CD_VAL_CD=PALT.PROV_ALTID_TRMNTN_RSN_CD\r\n" + 
			"WHERE P.PROV_CTGRY_CD='182'\r\n" + 
			")ALTID\r\n" + 
			"WHERE UPPER(ALTID_SOR_CD)='EPDSV2.0'\r\n" + 
			"AND UPPER(ALTID_TYPE_CD) IN ('EPDSV2 ID','PAYEE ID','Q/CARE TAX ID')\r\n" + 
			"AND MSTR_PROV_ID IN (<SPS_ID_LIST>)";

	public static final String SPS_GRP_ALT_ID_QUERY = "SELECT ALTID_SOR_CD\r\n" + 
			",ALTID_TYPE_CD\r\n" + 
			",ALTID_TXT\r\n" + 
			",GRPG_ALTID_EFCTV_DT\r\n" + 
			",GRPG_ALTID_TRMNTN_DT\r\n" + 
			",GRPG_ALTID_TRMNTN_RSN_CD\r\n" + 
			"FROM\r\n" + 
			"(\r\n" + 
			"SELECT COALESCE(XWALK1.CD_VAL_NM,' ') AS ALTID_SOR_CD\r\n" + 
			",COALESCE(XWALK2.CD_VAL_NM,' ') AS ALTID_TYPE_CD\r\n" + 
			",GALT.ALTID_TXT\r\n" + 
			",GALT.GRPG_ALTID_EFCTV_DT\r\n" + 
			",GALT.GRPG_ALTID_TRMNTN_DT\r\n" + 
			",COALESCE(XWALK3.CD_VAL_NM,'') AS GRPG_ALTID_TRMNTN_RSN_CD\r\n" + 
			",G.GRPG_ID\r\n" + 
			"FROM <SPS_DBNAME>.GRPG_ALT_IDFCTN GALT\r\n" + 
			"INNER JOIN <SPS_DBNAME>.GRPG G\r\n" + 
			"ON G.GRPG_ID=GALT.GRPG_ID\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_SOR_CD'\r\n" + 
			")XWALK1\r\n" + 
			"ON XWALK1.CD_VAL_CD=GALT.ALTID_SOR_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'ALTID_TYPE_CD'\r\n" + 
			")XWALK2\r\n" + 
			"ON XWALK2.CD_VAL_CD=GALT.ALTID_TYPE_CD\r\n" + 
			"LEFT OUTER JOIN\r\n" + 
			"(\r\n" + 
			"SELECT CD_VAL_CD, CD_VAL_NM\r\n" + 
			"FROM <SPS_DBNAME>.CD_VAL CDVAL\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_CLMN_ALS CLMN_ALS\r\n" + 
			"ON CDVAL.ITEM_ID= CLMN_ALS.ITEM_ID\r\n" + 
			"INNER JOIN <SPS_DBNAME>.BOT_ALS_CLMN_MAPG CLMN_ALS_MPG\r\n" + 
			"ON CLMN_ALS.CLMN_ALS_NM = CLMN_ALS_MPG.CLMN_ALS_NM\r\n" + 
			"WHERE UPPER(CLMN_ALS_MPG.CLMN_PHYSCL_NM) = 'GRPG_ALTID_TRMNTN_RSN_CD'\r\n" + 
			")XWALK3\r\n" + 
			"ON XWALK3.CD_VAL_CD=GALT.GRPG_ALTID_TRMNTN_RSN_CD\r\n" + 
			")ALTID\r\n" + 
			"WHERE UPPER(ALTID_SOR_CD)='EPDSV2.0'\r\n" + 
			"AND UPPER(ALTID_TYPE_CD)='LEGACY PROVIDER ID'\r\n" + 
			"AND GRPG_ID IN (<SPS_ID_LIST>)";

}
